name: "1. Quality Gate"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
      - 'feature/**'
      - 'feat/**'
      - 'hotfix/**'
      - 'fix/**'

jobs:
  quality-gate:
    strategy:
      fail-fast: false
      matrix:
        fixture:
          - fixtures/node-no-tests
          - fixtures/node-vitest
          # - fixtures/node-jest
          - fixtures/php-no-tests
          - fixtures/php-phpunit
          # - fixtures/dotnet-no-tests
          # - fixtures/dotnet-xunit
          # - fixtures/go-no-tests

    uses: heliomarpm/reusable-workflows/.github/workflows/ci-quality-gate.yml@main
    with:
      project-path: ${{ matrix.fixture }}
      coverage-min: 80
      coverage-mode: info