name: "2. Pull Request"
run-name: >-
  🔀 Auto PR: (${{ github.event.workflow_run.head_branch || github.ref_name }} → ${{
    startsWith(github.event.workflow_run.head_branch || github.ref_name, 'hotfix') && 'main' ||
    (startsWith(github.event.workflow_run.head_branch || github.ref_name, 'release') && 'main' ||
    ((github.event.workflow_run.head_branch == 'develop' || github.ref_name == 'develop') && 'release-*' || 'develop'))
  }}): ${{ github.event.workflow_run.head_commit.message || 'Disparo manual' }}


on:
  workflow_run:
    workflows: ["1. Quality Gate"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      strategy:
        description: 'Estratégia de PR (gitflow | trunk | develop)'
        required: false
        default: 'gitflow'

jobs:
  pull-request:
    if: >
      ${{
        github.event_name == 'workflow_dispatch' ||
        (github.event.workflow_run.conclusion == 'success' &&
         github.event.workflow_run.head_branch != 'main')
      }}
    uses: heliomarpm/reusable-workflows/.github/workflows/cd-pull-request.yml@main
    with:
      strategy: ${{ inputs.strategy || 'gitflow' }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}