name: "Changelog & Release"
on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - 'CHANGELOG.md'
  workflow_dispatch:
    inputs:
      create-release:
        description: 'Forçar criação de Git Tag e GitHub Release'
        type: boolean
        default: false
jobs:
  changelog:
    name: 📝 Update Changelog & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      # OBRIGATÓRIO: Clona o repositório com histórico completo para leitura de commits e tags
      - name: 📌 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # Executa o changelog
      - name: 📝 Update Changelog
        uses: heliomarpm/reusable-actions/actions/changelog@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}